[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "7vhyRo17pzQzqsbq4rmTLodRSaideJeKPtJPuprNCpaN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/jccervantes831/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
